# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ultra-satisfactory',
                'doc_host': 'https://lukedavisbbd.github.io',
                'git_url': 'https://github.com/lukedavisbbd/ultra-satisfactory',
                'lib_path': 'ultra_satisfactory'},
  'syms': { 'ultra_satisfactory.data': { 'ultra_satisfactory.data._find_static_dir': ( 'data.html#_find_static_dir',
                                                                                       'ultra_satisfactory/data.py'),
                                         'ultra_satisfactory.data.get_item_recipe': ( 'data.html#get_item_recipe',
                                                                                      'ultra_satisfactory/data.py'),
                                         'ultra_satisfactory.data.image_slug': ('data.html#image_slug', 'ultra_satisfactory/data.py'),
                                         'ultra_satisfactory.data.list_items': ('data.html#list_items', 'ultra_satisfactory/data.py'),
                                         'ultra_satisfactory.data.load_data': ('data.html#load_data', 'ultra_satisfactory/data.py'),
                                         'ultra_satisfactory.data.local_image_url': ( 'data.html#local_image_url',
                                                                                      'ultra_satisfactory/data.py'),
                                         'ultra_satisfactory.data.wiki_image_url': ( 'data.html#wiki_image_url',
                                                                                     'ultra_satisfactory/data.py')}}}
