"""Load and parse `data/data.json` from greeny/SatisfactoryTools into clean Python dicts."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_data.ipynb.

# %% auto #0
__all__ = ['load_data', 'wiki_image_url', 'image_slug', 'local_image_url', 'get_item_recipe', 'list_items']

# %% ../nbs/00_data.ipynb #7b488642
import json
from pathlib import Path

# %% ../nbs/00_data.ipynb #2c0d3d88
def load_data(data_path: str | Path = None) -> dict:
    """Load data.json and return the raw dict with keys: items, recipes, buildings, etc.
    
    If data_path is not provided, resolves relative to this file's location:
    walks up to find the repo root (where data/data.json lives).
    """
    if data_path is None:
        # Walk up from this file to find data/data.json
        here = Path(__file__).resolve().parent
        # Try up to 3 levels up
        for _ in range(4):
            candidate = here / 'data' / 'data.json'
            if candidate.exists():
                data_path = candidate
                break
            here = here.parent
        else:
            raise FileNotFoundError('data/data.json not found. Pass data_path explicitly.')
    with open(data_path, encoding='utf-8') as f:
        return json.load(f)

# %% ../nbs/00_data.ipynb #a365fc1b
def wiki_image_url(item_name: str, size: int = 128) -> str:
    """Return the wiki.gg thumbnail URL for an item by display name.
    
    Pattern: https://satisfactory.wiki.gg/images/thumb/{Name}.png/{size}px-{Name}.png
    Spaces are replaced with underscores.
    """
    slug = item_name.replace(' ', '_')
    return f'https://satisfactory.wiki.gg/images/thumb/{slug}.png/{size}px-{slug}.png'

# %% ../nbs/00_data.ipynb #d5e6f7a8
def image_slug(name: str) -> str:
    """Convert item display name to a filesystem-safe slug.

    Must match scripts/download_images.py exactly.
    """
    return name.replace(' ', '_').replace("'", '_').replace(':', '_')

# %% ../nbs/00_data.ipynb #e6f7a8b9
# ⚡ Resolve once at import time — works for both local dev and stlite
_STATIC_DIR: Path | None = None

def _find_static_dir() -> Path | None:
    """Locate app/static/images/ by walking up from this file."""
    here = Path(__file__).resolve().parent
    for _ in range(4):
        candidate = here / 'app' / 'static' / 'images'
        if candidate.is_dir():
            return candidate
        here = here.parent
    return None

_STATIC_DIR = _find_static_dir()


def local_image_url(item_name: str, size: int = 64) -> str:
    """Return local static URL if the image exists, else fall back to wiki.gg.

    Local path served by Streamlit: /app/static/images/{slug}.png
    The `size` parameter is ignored for local images (all cached at 64px)
    but passed through to wiki_image_url() as a fallback.
    """
    slug = image_slug(item_name)
    if _STATIC_DIR is not None and (_STATIC_DIR / f'{slug}.png').exists():
        return f'/app/static/images/{slug}.png'
    return wiki_image_url(item_name, size)

# %% ../nbs/00_data.ipynb #2444f397
def get_item_recipe(item_name: str, data: dict, alternate: bool = False) -> dict | None:
    """Look up an item by display name and return a clean recipe dict.

    Returns a dict with:
        name          -- item display name
        description   -- item description
        image_url     -- wiki.gg thumbnail URL
        ingredients   -- list of {name, amount, rate_per_min}
        products      -- list of {name, amount, rate_per_min}
        machine       -- building display name
        machine_power -- power draw in MW
        cycle_time    -- seconds per cycle
        recipe_name   -- recipe display name
        alternate     -- True if this is an alternate recipe

    If alternate=False (default), returns the standard (non-alternate) recipe.
    If alternate=True, returns the first alternate recipe found.
    Returns None if no matching item or recipe is found.
    """
    items = data.get('items', {})
    recipes = data.get('recipes', {})
    buildings = data.get('buildings', {})

    # Find item class key by display name
    item_key = None
    item_data = None
    for key, item in items.items():
        if item.get('name', '').lower() == item_name.lower():
            item_key = key
            item_data = item
            break
    if item_key is None:
        return None

    # Find matching recipe (standard or alternate)
    recipe_data = None
    for recipe in recipes.values():
        if not recipe.get('inMachine', False):
            continue
        products = recipe.get('products', [])
        if not any(p['item'] == item_key for p in products):
            continue
        is_alt = recipe.get('alternate', False)
        if is_alt == alternate:
            recipe_data = recipe
            break

    if recipe_data is None:
        return None

    cycle_time = recipe_data.get('time', 1)  # seconds
    cycles_per_min = 60.0 / cycle_time

    def resolve_ingredient(entry):
        """Resolve an ingredient/product entry to {name, amount, rate_per_min}."""
        ref_key = entry['item']
        amount = entry['amount']
        # Look up in items first, then resources
        ref_item = items.get(ref_key) or data.get('resources', {}).get(ref_key, {})
        return {
            'name': ref_item.get('name', ref_key),
            'amount': amount,
            'rate_per_min': round(amount * cycles_per_min, 4),
        }

    ingredients = [resolve_ingredient(e) for e in recipe_data.get('ingredients', [])]
    products = [resolve_ingredient(e) for e in recipe_data.get('products', [])]

    # Resolve machine
    produced_in = recipe_data.get('producedIn', [])
    machine_key = produced_in[0] if produced_in else None
    machine_data = buildings.get(machine_key, {}) if machine_key else {}
    machine_name = machine_data.get('name', machine_key or 'Unknown')
    machine_power = machine_data.get('metadata', {}).get('powerConsumption', 0)

    return {
        'name': item_data.get('name', item_name),
        'description': item_data.get('description', ''),
        'image_url': local_image_url(item_data.get('name', item_name)),
        'ingredients': ingredients,
        'products': products,
        'machine': machine_name,
        'machine_power': machine_power,
        'cycle_time': cycle_time,
        'recipe_name': recipe_data.get('name', ''),
        'alternate': recipe_data.get('alternate', False),
    }

# %% ../nbs/00_data.ipynb #c7d8e9f0
def list_items(data: dict, size: int = 40) -> list[dict]:
    """Return all craftable items sorted A-Z, excluding raw resources.

    Each entry is a dict with:
        class_key  -- internal class key from data.json
        name       -- display name
        image_url  -- local static URL (falls back to wiki.gg)

    Raw resources (data['resources']) are excluded — these are ore, water,
    etc. that cannot be crafted and have no recipe.
    """
    resource_keys = set(data.get('resources', {}).keys())
    items = [
        {
            'class_key': key,
            'name': item.get('name', key),
            'image_url': local_image_url(item.get('name', key)),
        }
        for key, item in data.get('items', {}).items()
        if key not in resource_keys
    ]
    return sorted(items, key=lambda x: x['name'].lower())
