"""Load and parse `data/data.json` from greeny/SatisfactoryTools into clean Python dicts."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_data.ipynb.

# %% auto #0
__all__ = ['load_data', 'wiki_image_url', 'image_slug', 'local_image_url', 'get_item_recipe', 'list_items', 'list_buildings',
           'get_building_unlock', 'get_upgrade_chain']

# %% ../nbs/00_data.ipynb #7b488642
import json
from pathlib import Path

# %% ../nbs/00_data.ipynb #2c0d3d88
def load_data(data_path: str | Path = None) -> dict:
    """Load data.json and return the raw dict with keys: items, recipes, buildings, etc.
    
    If data_path is not provided, resolves relative to this file's location:
    walks up to find the repo root (where data/data.json lives).
    """
    if data_path is None:
        # Walk up from this file to find data/data.json
        here = Path(__file__).resolve().parent
        # Try up to 3 levels up
        for _ in range(4):
            candidate = here / 'data' / 'data.json'
            if candidate.exists():
                data_path = candidate
                break
            here = here.parent
        else:
            raise FileNotFoundError('data/data.json not found. Pass data_path explicitly.')
    with open(data_path, encoding='utf-8') as f:
        return json.load(f)

# %% ../nbs/00_data.ipynb #a365fc1b
def wiki_image_url(item_name: str, size: int = 128) -> str:
    """Return the wiki.gg thumbnail URL for an item by display name.
    
    Pattern: https://satisfactory.wiki.gg/images/thumb/{Name}.png/{size}px-{Name}.png
    Spaces are replaced with underscores.
    """
    slug = item_name.replace(' ', '_')
    return f'https://satisfactory.wiki.gg/images/thumb/{slug}.png/{size}px-{slug}.png'

# %% ../nbs/00_data.ipynb #d5e6f7a8
def image_slug(name: str) -> str:
    """Convert item display name to a filesystem-safe slug.

    Must match scripts/download_images.py exactly.
    """
    return name.replace(' ', '_').replace("'", '_').replace(':', '_')

# %% ../nbs/00_data.ipynb #e6f7a8b9
# ⚡ Resolve once at import time — works for both local dev and stlite
_IMAGES_BASE: Path | None = None

def _find_images_base() -> Path | None:
    """Locate app/static/images/ by walking up from this file."""
    here = Path(__file__).resolve().parent
    for _ in range(4):
        candidate = here / 'app' / 'static' / 'images'
        if candidate.is_dir():
            return candidate
        here = here.parent
    return None

_IMAGES_BASE = _find_images_base()

# Available cached sizes (subdirectories under images/)
_CACHED_SIZES = [512, 256, 64]  # checked in order — prefer larger


def local_image_url(item_name: str, size: int = 64) -> str:
    """Return local static URL if the image exists, else fall back to wiki.gg.

    Images are stored in size subdirectories:
        /app/static/images/64/{slug}.png   -- thumbnails
        /app/static/images/256/{slug}.png  -- mid-res
        /app/static/images/512/{slug}.png  -- hero cards (retina-ready)

    Picks the smallest cached size >= requested size.
    Falls back to wiki.gg if no local file found.
    """
    slug = image_slug(item_name)
    if _IMAGES_BASE is not None:
        # Find best matching size: smallest cached size >= requested
        best = None
        for s in _CACHED_SIZES:
            path = _IMAGES_BASE / str(s) / f'{slug}.png'
            if path.exists():
                if s >= size:
                    best = s
                elif best is None:
                    best = s  # fallback to smaller if nothing bigger
        if best is not None:
            return f'/app/static/images/{best}/{slug}.png'
    return wiki_image_url(item_name, size)

# %% ../nbs/00_data.ipynb #2444f397
def get_item_recipe(item_name: str, data: dict, alternate: bool = False) -> dict | None:
    """Look up an item by display name and return a clean recipe dict.

    Returns a dict with:
        name          -- item display name
        description   -- item description
        image_url     -- wiki.gg thumbnail URL
        ingredients   -- list of {name, amount, rate_per_min}
        products      -- list of {name, amount, rate_per_min}
        machine       -- building display name
        machine_power -- power draw in MW
        cycle_time    -- seconds per cycle
        recipe_name   -- recipe display name
        alternate     -- True if this is an alternate recipe

    If alternate=False (default), returns the standard (non-alternate) recipe.
    If alternate=True, returns the first alternate recipe found.
    Returns None if no matching item or recipe is found.
    """
    items = data.get('items', {})
    recipes = data.get('recipes', {})
    buildings = data.get('buildings', {})

    # Find item class key by display name
    item_key = None
    item_data = None
    for key, item in items.items():
        if item.get('name', '').lower() == item_name.lower():
            item_key = key
            item_data = item
            break
    if item_key is None:
        return None

    # Find matching recipe (standard or alternate)
    recipe_data = None
    for recipe in recipes.values():
        if not recipe.get('inMachine', False):
            continue
        products = recipe.get('products', [])
        if not any(p['item'] == item_key for p in products):
            continue
        is_alt = recipe.get('alternate', False)
        if is_alt == alternate:
            recipe_data = recipe
            break

    if recipe_data is None:
        return None

    cycle_time = recipe_data.get('time', 1)  # seconds
    cycles_per_min = 60.0 / cycle_time

    def resolve_ingredient(entry):
        """Resolve an ingredient/product entry to {name, amount, rate_per_min}."""
        ref_key = entry['item']
        amount = entry['amount']
        # Look up in items first, then resources
        ref_item = items.get(ref_key) or data.get('resources', {}).get(ref_key, {})
        return {
            'name': ref_item.get('name', ref_key),
            'amount': amount,
            'rate_per_min': round(amount * cycles_per_min, 4),
        }

    ingredients = [resolve_ingredient(e) for e in recipe_data.get('ingredients', [])]
    products = [resolve_ingredient(e) for e in recipe_data.get('products', [])]

    # Resolve machine
    produced_in = recipe_data.get('producedIn', [])
    machine_key = produced_in[0] if produced_in else None
    machine_data = buildings.get(machine_key, {}) if machine_key else {}
    machine_name = machine_data.get('name', machine_key or 'Unknown')
    machine_power = machine_data.get('metadata', {}).get('powerConsumption', 0)

    return {
        'name': item_data.get('name', item_name),
        'description': item_data.get('description', ''),
        'image_url': local_image_url(item_data.get('name', item_name)),
        'ingredients': ingredients,
        'products': products,
        'machine': machine_name,
        'machine_power': machine_power,
        'cycle_time': cycle_time,
        'recipe_name': recipe_data.get('name', ''),
        'alternate': recipe_data.get('alternate', False),
    }

# %% ../nbs/00_data.ipynb #c7d8e9f0
def list_items(data: dict, size: int = 40) -> list[dict]:
    """Return all craftable items sorted A-Z, excluding raw resources.

    Each entry is a dict with:
        class_key  -- internal class key from data.json
        name       -- display name
        image_url  -- local static URL (falls back to wiki.gg)

    Raw resources (data['resources']) are excluded — these are ore, water,
    etc. that cannot be crafted and have no recipe.
    """
    resource_keys = set(data.get('resources', {}).keys())
    items = [
        {
            'class_key': key,
            'name': item.get('name', key),
            'image_url': local_image_url(item.get('name', key)),
        }
        for key, item in data.get('items', {}).items()
        if key not in resource_keys
    ]
    return sorted(items, key=lambda x: x['name'].lower())

# %% ../nbs/00_data.ipynb #d78a48c6
def list_buildings(data: dict) -> list[dict]:
    """Return all 477 player-buildable buildings sorted A-Z, each tagged with a category.

    Categories:
        production  -- manufacturing machines (manufacturingSpeed > 0)
        extraction  -- miners, water extractor, resource well
        power       -- generators + power infrastructure
        logistics   -- conveyors, pipelines, splitters, mergers, poles, supports
        storage     -- storage containers, fluid buffers
        transit     -- trains, trucks, drones, hypertube, jump pad
        special     -- hub, space elevator, awesome shop/sink, mam, craft bench
        structure   -- foundations, walls, ramps, roofs, catwalks, pillars, stairs
        decor       -- lights, signs, seasonal items, lookout tower

    Each entry dict:
        class_key      -- internal class key
        name           -- display name
        slug           -- building slug from data
        category       -- one of the 9 categories above
        power_mw       -- MW consumption (positive) or production (negative, generators)
        image_url      -- local static URL (64px) if cached, else wiki.gg URL
        image_url_large -- local static URL (512px) if cached, else wiki.gg URL
        tier           -- unlock tier (int), or None if unknown
        unlock_name    -- schematic display name, or None
        cost           -- list of {name, amount} build cost items
        description    -- building description text
    """
    buildings = data.get("buildings", {})
    miners = data.get("miners", {})
    generators = data.get("generators", {})
    items = data.get("items", {})
    resources = data.get("resources", {})
    recipes = data.get("recipes", {})
    schematics = data.get("schematics", {})

    # Reverse-lookup: building class_key -> unlock info, via forBuilding recipes
    bld_unlock = {}
    for sch in schematics.values():
        unlock_recipes = sch.get("unlock", {}).get("recipes", [])
        for rk in unlock_recipes:
            recipe = recipes.get(rk, {})
            if not recipe.get("forBuilding"):
                continue
            for prod in recipe.get("products", []):
                bk = prod["item"]
                if bk not in bld_unlock:
                    bld_unlock[bk] = {
                        "unlock_name": sch.get("name", ""),
                        "tier": sch.get("tier", 0),
                        "cost": sch.get("cost", []),
                    }

    def _cost_items(cost_list):
        result = []
        for entry in cost_list:
            item_key = entry.get("item", "")
            amount = entry.get("amount", 0)
            item_data = items.get(item_key) or resources.get(item_key, {})
            result.append({"name": item_data.get("name", item_key), "amount": amount})
        return result

    def _categorize(bkey, bval):
        meta = bval.get("metadata", {})
        mfg = meta.get("manufacturingSpeed", 0) or 0
        slug = bval.get("slug", "")
        name_lower = bval.get("name", "").lower()

        # Special named buildings first (before production check)
        if any(x in name_lower for x in [
            "the hub", "space elevator", "awesome shop", "awesome sink",
            "dimensional depot", "mam", "equipment workshop", "craft bench",
        ]):
            return "special"
        # Production machines
        if mfg > 0:
            return "production"
        # Extraction
        if bkey in miners or any(x in slug for x in ["water-extractor", "resource-well"]):
            return "extraction"
        # Generators
        if bkey in generators:
            return "power"
        # Power infrastructure
        if any(x in slug for x in [
            "power-pole", "power-line", "power-tower", "power-storage",
            "power-switch", "priority-power", "radar-tower",
            "biomass-burner", "coal-generator", "fuel-generator",
            "nuclear-power", "geothermal",
        ]):
            return "power"
        # Storage
        if any(x in slug for x in ["storage", "container", "fluid-buffer"]):
            return "storage"
        # Transit
        if any(x in slug for x in [
            "locomotive", "freight-car", "railway", "train-station",
            "truck-station", "tractor", "explorer", "drone-port",
            "cyber-wagon", "jump-pad", "landing-pad", "fluid-freight",
            "empty-platform",
        ]):
            return "transit"
        # Logistics
        if any(x in slug for x in [
            "conveyor", "pipeline", "splitter", "merger", "packager",
            "valve", "pump", "belt", "lift", "pole", "support",
            "floor-hole", "wall-hole", "wall-mount", "ceiling-mount",
            "wall-outlet", "block-signal", "path-signal", "automated-gate",
        ]):
            return "logistics"
        # Decor / lights / signs / seasonal
        if any(x in slug for x in [
            "light", "sign", "billboard", "display-sign", "ficsmas",
            "snowman", "candy-cane", "portrait-sign", "road-barrier",
            "lookout-tower", "ladder", "modern-railing",
        ]):
            return "decor"
        # Everything else is structure
        return "structure"

    def _power_mw(bkey, bval):
        meta = bval.get("metadata", {})
        if bkey in generators:
            gen = generators[bkey]
            return -(gen.get("powerProduction", 0) or 0)  # negative = produces
        return meta.get("powerConsumption", 0) or 0

    result = []
    for bkey, bval in buildings.items():
        cat = _categorize(bkey, bval)
        unlock = bld_unlock.get(bkey, {})
        power_mw = _power_mw(bkey, bval)
        cost_resolved = _cost_items(unlock.get("cost", []))
        name = bval.get("name", bkey)
        result.append({
            "class_key": bkey,
            "name": name,
            "slug": bval.get("slug", ""),
            "category": cat,
            "power_mw": power_mw,
            "image_url": local_image_url(name, 64),
            "image_url_large": local_image_url(name, 512),
            "tier": unlock.get("tier"),
            "unlock_name": unlock.get("unlock_name"),
            "cost": cost_resolved,
            "description": bval.get("description", ""),
        })

    return sorted(result, key=lambda x: x["name"].lower())


# %% ../nbs/00_data.ipynb #8e8d2d81
def get_building_unlock(class_name: str, data: dict) -> dict | None:
    """Return unlock info for a building by its class key.

    Searches for a forBuilding recipe whose product is class_name,
    then finds the schematic that unlocks that recipe.

    Returns:
        {schematic_name, tier, cost: [{name, amount}]}
    or None if not found.
    """
    recipes = data.get("recipes", {})
    schematics = data.get("schematics", {})
    items = data.get("items", {})
    resources = data.get("resources", {})

    # Find the forBuilding recipe for this building
    building_recipe_key = None
    for rk, rv in recipes.items():
        if not rv.get("forBuilding"):
            continue
        if any(p["item"] == class_name for p in rv.get("products", [])):
            building_recipe_key = rk
            break

    if building_recipe_key is None:
        return None

    # Find the schematic that unlocks this recipe
    for sch in schematics.values():
        if building_recipe_key in sch.get("unlock", {}).get("recipes", []):
            cost = []
            for entry in sch.get("cost", []):
                ik = entry.get("item", "")
                item_data = items.get(ik) or resources.get(ik, {})
                cost.append({"name": item_data.get("name", ik), "amount": entry.get("amount", 0)})
            return {
                "schematic_name": sch.get("name", ""),
                "tier": sch.get("tier", 0),
                "cost": cost,
            }

    return None


# %% ../nbs/00_data.ipynb
def get_building_produces(class_key: str, data: dict) -> list[dict]:
    """Return all items produceable by a building, grouped by unlock tier.

    Scans recipes where class_key is in producedIn, inMachine=True,
    forBuilding=False. For each product item, finds its earliest non-alternate
    unlock schematic to derive a tier_label (T0–T8, MAM, ALT, SHOP).

    Returns [{name, class_key, tier_label}], sorted by tier_label then A-Z by name.
    """
    recipes = data.get("recipes", {})
    items = data.get("items", {})
    resources = data.get("resources", {})
    schematics = data.get("schematics", {})

    def _label_from_unlock(sch: dict, recipe: dict) -> str:
        """Derive a tier label from one schematic+recipe unlock pair."""
        sch_type = sch.get("type", "")
        sch_tier = sch.get("tier", 0)
        is_mam = sch.get("mam", False)
        is_alternate = sch.get("alternate", False)
        recipe_is_alt = recipe.get("alternate", False)

        if recipe_is_alt or is_alternate or sch_type in ("EST_Alternate", "EST_HardDrive"):
            return "ALT"
        if is_mam or sch_type == "EST_MAM":
            return "MAM"
        if sch_type == "EST_ResourceSink":
            return "SHOP"
        return f"T{sch_tier}"

    # Tier sort order
    tier_order = {
        "T0": 0, "T1": 1, "T2": 2, "T3": 3, "T4": 4, "T5": 5, "T6": 6, "T7": 7, "T8": 8,
        "MAM": 9, "ALT": 10, "SHOP": 11
    }

    # Build a reverse-lookup: item_class_key -> best unlock label
    # Preference: earliest non-ALT unlock, then global tier label order.
    item_label = {}
    for sch in schematics.values():
        unlock_recipes = sch.get("unlock", {}).get("recipes", [])
        for rk in unlock_recipes:
            recipe = recipes.get(rk, {})
            if recipe.get("forBuilding"):
                continue
            label = _label_from_unlock(sch, recipe)
            label_rank = tier_order.get(label, 99)
            is_alt = label == "ALT"
            for prod in recipe.get("products", []):
                ik = prod["item"]
                if ik not in item_label:
                    item_label[ik] = (is_alt, label_rank, label)
                    continue
                prev_is_alt, prev_rank, _ = item_label[ik]
                if prev_is_alt and not is_alt:
                    item_label[ik] = (is_alt, label_rank, label)
                elif prev_is_alt == is_alt and label_rank < prev_rank:
                    item_label[ik] = (is_alt, label_rank, label)

    seen = set()
    result = []
    for rv in recipes.values():
        if not rv.get("inMachine"):
            continue
        if rv.get("forBuilding"):
            continue
        if class_key not in rv.get("producedIn", []):
            continue
        for p in rv.get("products", []):
            ck = p["item"]
            if ck in seen:
                continue
            seen.add(ck)
            item_data = items.get(ck) or resources.get(ck, {})
            name = item_data.get("name", ck)
            tier_label = item_label.get(ck, (False, 0, "T0"))[2]
            result.append({"name": name, "class_key": ck, "tier_label": tier_label})

    # Sort by tier_label order, then by name within tier
    return sorted(result, key=lambda x: (tier_order.get(x["tier_label"], 99), x["name"].lower()))


# %% ../nbs/00_data.ipynb #34039c13
def get_upgrade_chain(name_prefix: str, data: dict) -> list[dict]:
    """Return all Mk.N buildings matching name_prefix, sorted by Mk number.

    Finds buildings whose slug contains name_prefix and "-mk-".
    Each entry is the same shape as list_buildings() entries.

    Example:
        get_upgrade_chain("conveyor-belt", data)
        -> [Conveyor Belt Mk.1, Mk.2, Mk.3, Mk.4, Mk.5]

    Note: Pipeline has No Indicator variants -- callers may deduplicate by Mk number.
    """
    all_buildings = list_buildings(data)
    chain = [b for b in all_buildings if name_prefix in b["slug"] and "-mk-" in b["slug"]]

    def mk_num(b):
        slug = b["slug"]
        try:
            idx = slug.index("-mk-")
            return int(slug[idx + 4:].split("-")[0])
        except (ValueError, IndexError):
            return 99

    return sorted(chain, key=mk_num)
